feat: UI changes for Apicurio integration
streamshub/console pull request #1242
Opened 2024-11-26 11:56 UTC by hemahg

feat: UI changes for Apicurio integration

2024-12-02 16:01 UTC, MikeEdgar commented on ui/components/MessagesTable/MessagesTable.tsx
> +                                        >
It seems a little funky to nest the schema under the topic messages, but I realize that there aren't really any alternatives given what the API is returning for the link. Maybe in a future PR the API can return the registry name and schema ID as separate fields and the pages no longer need to be nested this way.

2024-12-03 20:02 UTC, hemahg commented on ui/api/schema/action.ts
> +  const rawData = await res.json();
fixed

2024-12-03 20:02 UTC, hemahg commented on ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/[...content]/page.tsx
> +      content={JSON.stringify(content, null, 2)}
fixed

2024-12-03 20:03 UTC, hemahg commented on ui/components/MessagesTable/components/MessageDetails.tsx
> +              {message.relationships.keySchema?.meta?.artifactType}
updated

2024-12-03 20:03 UTC, hemahg commented on ui/components/MessagesTable/components/MessageDetails.tsx
> +              {message.relationships.valueSchema?.meta?.artifactType}
Done

2024-12-04 00:50 UTC, MikeEdgar requested changes
Very nice, there is just one typo that I noticed. Otherwise I think we can merge. Thanks

2024-12-04 00:50 UTC, MikeEdgar commented on ui/components/MessagesTable/MessagesTable.tsx
> +                                          href={`${baseurl}/schema/content=${encodeURIComponent(row.relationships.keySchema?.links?.content)}&schemaname=${encodeURIComponent(
```suggestion
                                          href={`${baseurl}/schema?content=${encodeURIComponent(row.relationships.keySchema?.links?.content)}&schemaname=${encodeURIComponent(
```

2024-12-04 11:47 UTC, hemahg commented on ui/components/MessagesTable/MessagesTable.tsx
> +                                          href={`${baseurl}/schema/content=${encodeURIComponent(row.relationships.keySchema?.links?.content)}&schemaname=${encodeURIComponent(
sorry, fixed it

2024-12-04 12:13 UTC, MikeEdgar approved these changes
:+1:

2024-12-04 13:38 UTC, merged